### PR TITLE
resolves #16

### LINKED ISSUE #16: Frontend container wrong port
Hello,

The frontend is listening to port 80 not 8080.

Thanks

### PR DESCRIPTION
**Pull request by norweeg**
updates incorrect port mapping for ui container in:

README.md
docker-compose.yml
docker-compose.override.dev.yml
docker-compose.override.example.yml

### CODE REVIEW

**Comment by norweeg** [comment]
Please see [/frontend/default.conf](https://github.com/snypy/snypy-docker/blob/main/frontend/default.conf).  The configured listening port for the UI container is 80, but all compose files and the example nginx configuration for external access show port 8080, which is not correct.

**Comment by nezhar** [comment]
port `8080` is intentional, as this is the port of the ui container.

Your proxy should forward from `80` to `8080` for the ui.

**Comment by norweeg** [comment]
> port `8080` is intentional, as this is the port of the ui container.
> 
> Your proxy should forward from `80` to `8080` for the ui.

I don't think you read the issue correctly.  the problem is that the container is listening on port 80, not 8080.  forwarding to port 8080 will result in an error because, as written, the container is listening on port 80 and this PR was to address that by changing it to 8080

**Comment by nezhar** [comment]
You should encounter no errors while setting up Nginx with the configuration suggested. I've created a quick graph for clarity; I hope it helps.

ports drawio

1. Traffic enters on "app.snypy.com" on ports 80 and 443.
2. This traffic is then received by the host's Nginx server, which is set to listen on ports 80 and 443.
3. The host's Nginx server then directs the traffic to a frontend container via port 8080.
4. Inside the frontend container, there is a port mapping from 8080 to 80.
5. The Nginx server inside the container, which is listening on port 80, then handles the incoming traffic.

**Pull request closed without merging**
